# docker-compose.yml
version: '3.8'

services:
  # Ethereum RPC Proxy
  ethereum-rpc:
    build: 
      context: .
      dockerfile: Dockerfile.rpc-proxy
    environment:
      - BLOCKCHAIN_CHAIN=ethereum
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - VAULT_TOKEN=${VAULT_TOKEN}
    volumes:
      - blockchain_config:/opt/config:ro  # Read-only config
      - wallet_storage:/opt/peatio/wallets
    ports:
      - "8545:8545"
    command: ["bundle", "exec", "ruby", "lib/rpc_proxy_server.rb"]
    
  # Polygon RPC Proxy  
  polygon-rpc:
    build:
      context: .
      dockerfile: Dockerfile.rpc-proxy
    environment:
      - BLOCKCHAIN_CHAIN=polygon
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - VAULT_TOKEN=${VAULT_TOKEN}
    volumes:
      - blockchain_config:/opt/config:ro
      - wallet_storage:/opt/peatio/wallets
    ports:
      - "8546:8545"  # Internal port 8545, external 8546
    command: ["bundle", "exec", "ruby", "lib/rpc_proxy_server.rb"]
    
  # BSC RPC Proxy
  bsc-rpc:
    build:
      context: .  
      dockerfile: Dockerfile.rpc-proxy
    environment:
      - BLOCKCHAIN_CHAIN=bsc
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - VAULT_TOKEN=${VAULT_TOKEN}
    volumes:
      - blockchain_config:/opt/config:ro
      - wallet_storage:/opt/peatio/wallets
    ports:
      - "8547:8545"
    command: ["bundle", "exec", "ruby", "lib/rpc_proxy_server.rb"]
    
  # Arbitrum RPC Proxy
  arbitrum-rpc:
    build:
      context: .
      dockerfile: Dockerfile.rpc-proxy
    environment:
      - BLOCKCHAIN_CHAIN=arbitrum
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - VAULT_TOKEN=${VAULT_TOKEN}
    volumes:
      - blockchain_config:/opt/config:ro
      - wallet_storage:/opt/peatio/wallets
    ports:
      - "8548:8545"
    command: ["bundle", "exec", "ruby", "lib/rpc_proxy_server.rb"]

  # Main Peatio application
  peatio:
    image: your-peatio-image
    depends_on:
      - ethereum-rpc
      - polygon-rpc
      - bsc-rpc
      - arbitrum-rpc
    environment:
      - ETH_RPC_URL=http://ethereum-rpc:8545
      - POLYGON_RPC_URL=http://polygon-rpc:8545
      - BSC_RPC_URL=http://bsc-rpc:8545
      - ARBITRUM_RPC_URL=http://arbitrum-rpc:8545

volumes:
  # Configuration shared across all containers (read-only)
  blockchain_config:
    driver: local
    driver_opts:
      type: none
      o: bind,ro  # Read-only mount
      device: /opt/opendax/config
      
  # Wallet files shared across all containers
  wallet_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/opendax/wallets

